version: "3.7"

services:
    node:
        container_name: homepage
        image: homepage
        build:
            context: .
            dockerfile: Dockerfile
        # depends_on:
        #     - ipfs
        volumes:
            - .:/var/www/public
        environment:
            - NODE_ENV=development
        ports:
            - "8080:3001"
        # networks:
        #     - nodetest-network
    # ipfs:
    #     container_name: lalalala
    #     image: ipfs
    #     build:
    #         context: .
    #         dockerfile: Dockerfile.ipfs
    #     restart: always
    #     networks:
    #         - nodetest-network
# networks:
#     nodetest-network:
#         driver: bridge
